// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxappmetrics.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the MxAppMetrics module

	public static java.lang.String getAPP_METRICS_VERSION()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MxAppMetrics.APP_METRICS_VERSION");
	}
}