// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the Main module

	public static java.lang.String getAWS_S3_BUCKET()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Main.AWS_S3_BUCKET");
	}

	public static java.lang.String getCONFIG_NAME()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Main.CONFIG_NAME");
	}
}