// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package main.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class CleanupSlackMessage extends CustomJavaAction<java.lang.String>
{
	private java.lang.String Message;

	public CleanupSlackMessage(IContext context, java.lang.String Message)
	{
		super(context);
		this.Message = Message;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
        String pattern = "<[^>]*>";
        String cleanMessage = this.Message.replaceAll(pattern, "");
        return cleanMessage;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CleanupSlackMessage";
	}

	// BEGIN EXTRA CODE

	// END EXTRA CODE
}
