// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package main.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import java.util.HashMap;
import java.util.Map;

public class SetConstant extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String Name;
	private java.lang.String Value;

	public SetConstant(IContext context, java.lang.String Name, java.lang.String Value)
	{
		super(context);
		this.Name = Name;
		this.Value = Value;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        logger.info(String.format("Setting config for %s to %s", Name, Value));
        logger.info(String.format("Current value %s = %s",Name,Core.getConfiguration().getConstantValue(Name)));
        Map<String, Object> config = new HashMap<String, Object>();
        config.put(Name, Value);
        Core.getConfiguration().updateConfiguration(config, true);
        logger.info(String.format("Current value %s = %s",Name,Core.getConfiguration().getConstantValue(Name)));
        //throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
        return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "SetConstant";
	}

	// BEGIN EXTRA CODE
    private static final ILogNode logger = Core.getLogger(SetConstant.class.getName());
	// END EXTRA CODE
}
