// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies;

public class Config
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject configMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Main.Config";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		AwsRegion("AwsRegion"),
		AwsAccessKeyId("AwsAccessKeyId"),
		AwsSecretAccessKey("AwsSecretAccessKey"),
		AwsLexRegion("AwsLexRegion"),
		AwsLexAccessKeyId("AwsLexAccessKeyId"),
		AwsLexSecretAccessKey("AwsLexSecretAccessKey"),
		GoogleAnalyticsTrackingId("GoogleAnalyticsTrackingId"),
		MixPanelProjectToken("MixPanelProjectToken"),
		SlackToken("SlackToken");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Config(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Main.Config"));
	}

	protected Config(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject configMendixObject)
	{
		if (configMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Main.Config", configMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Main.Config");

		this.configMendixObject = configMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Config.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static main.proxies.Config initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return main.proxies.Config.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static main.proxies.Config initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new main.proxies.Config(context, mendixObject);
	}

	public static main.proxies.Config load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return main.proxies.Config.initialize(context, mendixObject);
	}

	public static java.util.List<main.proxies.Config> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<main.proxies.Config> result = new java.util.ArrayList<main.proxies.Config>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Main.Config" + xpathConstraint))
			result.add(main.proxies.Config.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of AwsRegion
	 */
	public final java.lang.String getAwsRegion()
	{
		return getAwsRegion(getContext());
	}

	/**
	 * @param context
	 * @return value of AwsRegion
	 */
	public final java.lang.String getAwsRegion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AwsRegion.toString());
	}

	/**
	 * Set value of AwsRegion
	 * @param awsregion
	 */
	public final void setAwsRegion(java.lang.String awsregion)
	{
		setAwsRegion(getContext(), awsregion);
	}

	/**
	 * Set value of AwsRegion
	 * @param context
	 * @param awsregion
	 */
	public final void setAwsRegion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String awsregion)
	{
		getMendixObject().setValue(context, MemberNames.AwsRegion.toString(), awsregion);
	}

	/**
	 * @return value of AwsAccessKeyId
	 */
	public final java.lang.String getAwsAccessKeyId()
	{
		return getAwsAccessKeyId(getContext());
	}

	/**
	 * @param context
	 * @return value of AwsAccessKeyId
	 */
	public final java.lang.String getAwsAccessKeyId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AwsAccessKeyId.toString());
	}

	/**
	 * Set value of AwsAccessKeyId
	 * @param awsaccesskeyid
	 */
	public final void setAwsAccessKeyId(java.lang.String awsaccesskeyid)
	{
		setAwsAccessKeyId(getContext(), awsaccesskeyid);
	}

	/**
	 * Set value of AwsAccessKeyId
	 * @param context
	 * @param awsaccesskeyid
	 */
	public final void setAwsAccessKeyId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String awsaccesskeyid)
	{
		getMendixObject().setValue(context, MemberNames.AwsAccessKeyId.toString(), awsaccesskeyid);
	}

	/**
	 * @return value of AwsSecretAccessKey
	 */
	public final java.lang.String getAwsSecretAccessKey()
	{
		return getAwsSecretAccessKey(getContext());
	}

	/**
	 * @param context
	 * @return value of AwsSecretAccessKey
	 */
	public final java.lang.String getAwsSecretAccessKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AwsSecretAccessKey.toString());
	}

	/**
	 * Set value of AwsSecretAccessKey
	 * @param awssecretaccesskey
	 */
	public final void setAwsSecretAccessKey(java.lang.String awssecretaccesskey)
	{
		setAwsSecretAccessKey(getContext(), awssecretaccesskey);
	}

	/**
	 * Set value of AwsSecretAccessKey
	 * @param context
	 * @param awssecretaccesskey
	 */
	public final void setAwsSecretAccessKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String awssecretaccesskey)
	{
		getMendixObject().setValue(context, MemberNames.AwsSecretAccessKey.toString(), awssecretaccesskey);
	}

	/**
	 * @return value of AwsLexRegion
	 */
	public final java.lang.String getAwsLexRegion()
	{
		return getAwsLexRegion(getContext());
	}

	/**
	 * @param context
	 * @return value of AwsLexRegion
	 */
	public final java.lang.String getAwsLexRegion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AwsLexRegion.toString());
	}

	/**
	 * Set value of AwsLexRegion
	 * @param awslexregion
	 */
	public final void setAwsLexRegion(java.lang.String awslexregion)
	{
		setAwsLexRegion(getContext(), awslexregion);
	}

	/**
	 * Set value of AwsLexRegion
	 * @param context
	 * @param awslexregion
	 */
	public final void setAwsLexRegion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String awslexregion)
	{
		getMendixObject().setValue(context, MemberNames.AwsLexRegion.toString(), awslexregion);
	}

	/**
	 * @return value of AwsLexAccessKeyId
	 */
	public final java.lang.String getAwsLexAccessKeyId()
	{
		return getAwsLexAccessKeyId(getContext());
	}

	/**
	 * @param context
	 * @return value of AwsLexAccessKeyId
	 */
	public final java.lang.String getAwsLexAccessKeyId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AwsLexAccessKeyId.toString());
	}

	/**
	 * Set value of AwsLexAccessKeyId
	 * @param awslexaccesskeyid
	 */
	public final void setAwsLexAccessKeyId(java.lang.String awslexaccesskeyid)
	{
		setAwsLexAccessKeyId(getContext(), awslexaccesskeyid);
	}

	/**
	 * Set value of AwsLexAccessKeyId
	 * @param context
	 * @param awslexaccesskeyid
	 */
	public final void setAwsLexAccessKeyId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String awslexaccesskeyid)
	{
		getMendixObject().setValue(context, MemberNames.AwsLexAccessKeyId.toString(), awslexaccesskeyid);
	}

	/**
	 * @return value of AwsLexSecretAccessKey
	 */
	public final java.lang.String getAwsLexSecretAccessKey()
	{
		return getAwsLexSecretAccessKey(getContext());
	}

	/**
	 * @param context
	 * @return value of AwsLexSecretAccessKey
	 */
	public final java.lang.String getAwsLexSecretAccessKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AwsLexSecretAccessKey.toString());
	}

	/**
	 * Set value of AwsLexSecretAccessKey
	 * @param awslexsecretaccesskey
	 */
	public final void setAwsLexSecretAccessKey(java.lang.String awslexsecretaccesskey)
	{
		setAwsLexSecretAccessKey(getContext(), awslexsecretaccesskey);
	}

	/**
	 * Set value of AwsLexSecretAccessKey
	 * @param context
	 * @param awslexsecretaccesskey
	 */
	public final void setAwsLexSecretAccessKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String awslexsecretaccesskey)
	{
		getMendixObject().setValue(context, MemberNames.AwsLexSecretAccessKey.toString(), awslexsecretaccesskey);
	}

	/**
	 * @return value of GoogleAnalyticsTrackingId
	 */
	public final java.lang.String getGoogleAnalyticsTrackingId()
	{
		return getGoogleAnalyticsTrackingId(getContext());
	}

	/**
	 * @param context
	 * @return value of GoogleAnalyticsTrackingId
	 */
	public final java.lang.String getGoogleAnalyticsTrackingId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GoogleAnalyticsTrackingId.toString());
	}

	/**
	 * Set value of GoogleAnalyticsTrackingId
	 * @param googleanalyticstrackingid
	 */
	public final void setGoogleAnalyticsTrackingId(java.lang.String googleanalyticstrackingid)
	{
		setGoogleAnalyticsTrackingId(getContext(), googleanalyticstrackingid);
	}

	/**
	 * Set value of GoogleAnalyticsTrackingId
	 * @param context
	 * @param googleanalyticstrackingid
	 */
	public final void setGoogleAnalyticsTrackingId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String googleanalyticstrackingid)
	{
		getMendixObject().setValue(context, MemberNames.GoogleAnalyticsTrackingId.toString(), googleanalyticstrackingid);
	}

	/**
	 * @return value of MixPanelProjectToken
	 */
	public final java.lang.String getMixPanelProjectToken()
	{
		return getMixPanelProjectToken(getContext());
	}

	/**
	 * @param context
	 * @return value of MixPanelProjectToken
	 */
	public final java.lang.String getMixPanelProjectToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MixPanelProjectToken.toString());
	}

	/**
	 * Set value of MixPanelProjectToken
	 * @param mixpanelprojecttoken
	 */
	public final void setMixPanelProjectToken(java.lang.String mixpanelprojecttoken)
	{
		setMixPanelProjectToken(getContext(), mixpanelprojecttoken);
	}

	/**
	 * Set value of MixPanelProjectToken
	 * @param context
	 * @param mixpanelprojecttoken
	 */
	public final void setMixPanelProjectToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mixpanelprojecttoken)
	{
		getMendixObject().setValue(context, MemberNames.MixPanelProjectToken.toString(), mixpanelprojecttoken);
	}

	/**
	 * @return value of SlackToken
	 */
	public final java.lang.String getSlackToken()
	{
		return getSlackToken(getContext());
	}

	/**
	 * @param context
	 * @return value of SlackToken
	 */
	public final java.lang.String getSlackToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SlackToken.toString());
	}

	/**
	 * Set value of SlackToken
	 * @param slacktoken
	 */
	public final void setSlackToken(java.lang.String slacktoken)
	{
		setSlackToken(getContext(), slacktoken);
	}

	/**
	 * Set value of SlackToken
	 * @param context
	 * @param slacktoken
	 */
	public final void setSlackToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String slacktoken)
	{
		getMendixObject().setValue(context, MemberNames.SlackToken.toString(), slacktoken);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return configMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final main.proxies.Config that = (main.proxies.Config) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Main.Config";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
