// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies;

public class Face
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject faceMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Main.Face";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AgeLow("AgeLow"),
		AgeHigh("AgeHigh"),
		BoundingBoxTop("BoundingBoxTop"),
		BoundingBoxLeft("BoundingBoxLeft"),
		BoundingBoxWidth("BoundingBoxWidth"),
		BoundingBoxHeight("BoundingBoxHeight"),
		Brightness("Brightness"),
		Sharpness("Sharpness"),
		Face_SlackImageRecognitionRequest("Main.Face_SlackImageRecognitionRequest");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Face(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Main.Face"));
	}

	protected Face(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject faceMendixObject)
	{
		if (faceMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Main.Face", faceMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Main.Face");

		this.faceMendixObject = faceMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Face.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static main.proxies.Face initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return main.proxies.Face.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static main.proxies.Face initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new main.proxies.Face(context, mendixObject);
	}

	public static main.proxies.Face load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return main.proxies.Face.initialize(context, mendixObject);
	}

	public static java.util.List<main.proxies.Face> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<main.proxies.Face> result = new java.util.ArrayList<main.proxies.Face>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Main.Face" + xpathConstraint))
			result.add(main.proxies.Face.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of AgeLow
	 */
	public final java.lang.Integer getAgeLow()
	{
		return getAgeLow(getContext());
	}

	/**
	 * @param context
	 * @return value of AgeLow
	 */
	public final java.lang.Integer getAgeLow(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.AgeLow.toString());
	}

	/**
	 * Set value of AgeLow
	 * @param agelow
	 */
	public final void setAgeLow(java.lang.Integer agelow)
	{
		setAgeLow(getContext(), agelow);
	}

	/**
	 * Set value of AgeLow
	 * @param context
	 * @param agelow
	 */
	public final void setAgeLow(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer agelow)
	{
		getMendixObject().setValue(context, MemberNames.AgeLow.toString(), agelow);
	}

	/**
	 * @return value of AgeHigh
	 */
	public final java.lang.Integer getAgeHigh()
	{
		return getAgeHigh(getContext());
	}

	/**
	 * @param context
	 * @return value of AgeHigh
	 */
	public final java.lang.Integer getAgeHigh(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.AgeHigh.toString());
	}

	/**
	 * Set value of AgeHigh
	 * @param agehigh
	 */
	public final void setAgeHigh(java.lang.Integer agehigh)
	{
		setAgeHigh(getContext(), agehigh);
	}

	/**
	 * Set value of AgeHigh
	 * @param context
	 * @param agehigh
	 */
	public final void setAgeHigh(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer agehigh)
	{
		getMendixObject().setValue(context, MemberNames.AgeHigh.toString(), agehigh);
	}

	/**
	 * @return value of BoundingBoxTop
	 */
	public final java.math.BigDecimal getBoundingBoxTop()
	{
		return getBoundingBoxTop(getContext());
	}

	/**
	 * @param context
	 * @return value of BoundingBoxTop
	 */
	public final java.math.BigDecimal getBoundingBoxTop(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.BoundingBoxTop.toString());
	}

	/**
	 * Set value of BoundingBoxTop
	 * @param boundingboxtop
	 */
	public final void setBoundingBoxTop(java.math.BigDecimal boundingboxtop)
	{
		setBoundingBoxTop(getContext(), boundingboxtop);
	}

	/**
	 * Set value of BoundingBoxTop
	 * @param context
	 * @param boundingboxtop
	 */
	public final void setBoundingBoxTop(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal boundingboxtop)
	{
		getMendixObject().setValue(context, MemberNames.BoundingBoxTop.toString(), boundingboxtop);
	}

	/**
	 * @return value of BoundingBoxLeft
	 */
	public final java.math.BigDecimal getBoundingBoxLeft()
	{
		return getBoundingBoxLeft(getContext());
	}

	/**
	 * @param context
	 * @return value of BoundingBoxLeft
	 */
	public final java.math.BigDecimal getBoundingBoxLeft(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.BoundingBoxLeft.toString());
	}

	/**
	 * Set value of BoundingBoxLeft
	 * @param boundingboxleft
	 */
	public final void setBoundingBoxLeft(java.math.BigDecimal boundingboxleft)
	{
		setBoundingBoxLeft(getContext(), boundingboxleft);
	}

	/**
	 * Set value of BoundingBoxLeft
	 * @param context
	 * @param boundingboxleft
	 */
	public final void setBoundingBoxLeft(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal boundingboxleft)
	{
		getMendixObject().setValue(context, MemberNames.BoundingBoxLeft.toString(), boundingboxleft);
	}

	/**
	 * @return value of BoundingBoxWidth
	 */
	public final java.math.BigDecimal getBoundingBoxWidth()
	{
		return getBoundingBoxWidth(getContext());
	}

	/**
	 * @param context
	 * @return value of BoundingBoxWidth
	 */
	public final java.math.BigDecimal getBoundingBoxWidth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.BoundingBoxWidth.toString());
	}

	/**
	 * Set value of BoundingBoxWidth
	 * @param boundingboxwidth
	 */
	public final void setBoundingBoxWidth(java.math.BigDecimal boundingboxwidth)
	{
		setBoundingBoxWidth(getContext(), boundingboxwidth);
	}

	/**
	 * Set value of BoundingBoxWidth
	 * @param context
	 * @param boundingboxwidth
	 */
	public final void setBoundingBoxWidth(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal boundingboxwidth)
	{
		getMendixObject().setValue(context, MemberNames.BoundingBoxWidth.toString(), boundingboxwidth);
	}

	/**
	 * @return value of BoundingBoxHeight
	 */
	public final java.math.BigDecimal getBoundingBoxHeight()
	{
		return getBoundingBoxHeight(getContext());
	}

	/**
	 * @param context
	 * @return value of BoundingBoxHeight
	 */
	public final java.math.BigDecimal getBoundingBoxHeight(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.BoundingBoxHeight.toString());
	}

	/**
	 * Set value of BoundingBoxHeight
	 * @param boundingboxheight
	 */
	public final void setBoundingBoxHeight(java.math.BigDecimal boundingboxheight)
	{
		setBoundingBoxHeight(getContext(), boundingboxheight);
	}

	/**
	 * Set value of BoundingBoxHeight
	 * @param context
	 * @param boundingboxheight
	 */
	public final void setBoundingBoxHeight(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal boundingboxheight)
	{
		getMendixObject().setValue(context, MemberNames.BoundingBoxHeight.toString(), boundingboxheight);
	}

	/**
	 * @return value of Brightness
	 */
	public final java.math.BigDecimal getBrightness()
	{
		return getBrightness(getContext());
	}

	/**
	 * @param context
	 * @return value of Brightness
	 */
	public final java.math.BigDecimal getBrightness(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Brightness.toString());
	}

	/**
	 * Set value of Brightness
	 * @param brightness
	 */
	public final void setBrightness(java.math.BigDecimal brightness)
	{
		setBrightness(getContext(), brightness);
	}

	/**
	 * Set value of Brightness
	 * @param context
	 * @param brightness
	 */
	public final void setBrightness(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal brightness)
	{
		getMendixObject().setValue(context, MemberNames.Brightness.toString(), brightness);
	}

	/**
	 * @return value of Sharpness
	 */
	public final java.math.BigDecimal getSharpness()
	{
		return getSharpness(getContext());
	}

	/**
	 * @param context
	 * @return value of Sharpness
	 */
	public final java.math.BigDecimal getSharpness(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Sharpness.toString());
	}

	/**
	 * Set value of Sharpness
	 * @param sharpness
	 */
	public final void setSharpness(java.math.BigDecimal sharpness)
	{
		setSharpness(getContext(), sharpness);
	}

	/**
	 * Set value of Sharpness
	 * @param context
	 * @param sharpness
	 */
	public final void setSharpness(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal sharpness)
	{
		getMendixObject().setValue(context, MemberNames.Sharpness.toString(), sharpness);
	}

	/**
	 * @return value of Face_SlackImageRecognitionRequest
	 */
	public final main.proxies.SlackImageRecognitionRequest getFace_SlackImageRecognitionRequest() throws com.mendix.core.CoreException
	{
		return getFace_SlackImageRecognitionRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of Face_SlackImageRecognitionRequest
	 */
	public final main.proxies.SlackImageRecognitionRequest getFace_SlackImageRecognitionRequest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.SlackImageRecognitionRequest result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Face_SlackImageRecognitionRequest.toString());
		if (identifier != null)
			result = main.proxies.SlackImageRecognitionRequest.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Face_SlackImageRecognitionRequest
	 * @param face_slackimagerecognitionrequest
	 */
	public final void setFace_SlackImageRecognitionRequest(main.proxies.SlackImageRecognitionRequest face_slackimagerecognitionrequest)
	{
		setFace_SlackImageRecognitionRequest(getContext(), face_slackimagerecognitionrequest);
	}

	/**
	 * Set value of Face_SlackImageRecognitionRequest
	 * @param context
	 * @param face_slackimagerecognitionrequest
	 */
	public final void setFace_SlackImageRecognitionRequest(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.SlackImageRecognitionRequest face_slackimagerecognitionrequest)
	{
		if (face_slackimagerecognitionrequest == null)
			getMendixObject().setValue(context, MemberNames.Face_SlackImageRecognitionRequest.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Face_SlackImageRecognitionRequest.toString(), face_slackimagerecognitionrequest.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return faceMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final main.proxies.Face that = (main.proxies.Face) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Main.Face";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
