// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies;

public class FindImageResult
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject findImageResultMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Main.FindImageResult";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FindImageResult_SlackMessageReceived("Main.FindImageResult_SlackMessageReceived"),
		FindImageResult_Label("Main.FindImageResult_Label");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FindImageResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Main.FindImageResult"));
	}

	protected FindImageResult(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject findImageResultMendixObject)
	{
		if (findImageResultMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Main.FindImageResult", findImageResultMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Main.FindImageResult");

		this.findImageResultMendixObject = findImageResultMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'FindImageResult.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static main.proxies.FindImageResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return main.proxies.FindImageResult.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static main.proxies.FindImageResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new main.proxies.FindImageResult(context, mendixObject);
	}

	public static main.proxies.FindImageResult load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return main.proxies.FindImageResult.initialize(context, mendixObject);
	}

	public static java.util.List<main.proxies.FindImageResult> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<main.proxies.FindImageResult> result = new java.util.ArrayList<main.proxies.FindImageResult>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Main.FindImageResult" + xpathConstraint))
			result.add(main.proxies.FindImageResult.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of FindImageResult_SlackMessageReceived
	 */
	public final main.proxies.SlackMessageReceived getFindImageResult_SlackMessageReceived() throws com.mendix.core.CoreException
	{
		return getFindImageResult_SlackMessageReceived(getContext());
	}

	/**
	 * @param context
	 * @return value of FindImageResult_SlackMessageReceived
	 */
	public final main.proxies.SlackMessageReceived getFindImageResult_SlackMessageReceived(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.SlackMessageReceived result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FindImageResult_SlackMessageReceived.toString());
		if (identifier != null)
			result = main.proxies.SlackMessageReceived.load(context, identifier);
		return result;
	}

	/**
	 * Set value of FindImageResult_SlackMessageReceived
	 * @param findimageresult_slackmessagereceived
	 */
	public final void setFindImageResult_SlackMessageReceived(main.proxies.SlackMessageReceived findimageresult_slackmessagereceived)
	{
		setFindImageResult_SlackMessageReceived(getContext(), findimageresult_slackmessagereceived);
	}

	/**
	 * Set value of FindImageResult_SlackMessageReceived
	 * @param context
	 * @param findimageresult_slackmessagereceived
	 */
	public final void setFindImageResult_SlackMessageReceived(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.SlackMessageReceived findimageresult_slackmessagereceived)
	{
		if (findimageresult_slackmessagereceived == null)
			getMendixObject().setValue(context, MemberNames.FindImageResult_SlackMessageReceived.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.FindImageResult_SlackMessageReceived.toString(), findimageresult_slackmessagereceived.getMendixObject().getId());
	}

	/**
	 * @return value of FindImageResult_Label
	 */
	public final java.util.List<main.proxies.Label> getFindImageResult_Label() throws com.mendix.core.CoreException
	{
		return getFindImageResult_Label(getContext());
	}

	/**
	 * @param context
	 * @return value of FindImageResult_Label
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<main.proxies.Label> getFindImageResult_Label(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<main.proxies.Label> result = new java.util.ArrayList<main.proxies.Label>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.FindImageResult_Label.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(main.proxies.Label.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of FindImageResult_Label
	 * @param findimageresult_label
	 */
	public final void setFindImageResult_Label(java.util.List<main.proxies.Label> findimageresult_label)
	{
		setFindImageResult_Label(getContext(), findimageresult_label);
	}

	/**
	 * Set value of FindImageResult_Label
	 * @param context
	 * @param findimageresult_label
	 */
	public final void setFindImageResult_Label(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<main.proxies.Label> findimageresult_label)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (main.proxies.Label proxyObject : findimageresult_label)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.FindImageResult_Label.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return findImageResultMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final main.proxies.FindImageResult that = (main.proxies.FindImageResult) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Main.FindImageResult";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
