// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies;

public class Label
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject labelMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Main.Label";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Confidence("Confidence"),
		image_labels("Main.image_labels");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Label(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Main.Label"));
	}

	protected Label(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject labelMendixObject)
	{
		if (labelMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Main.Label", labelMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Main.Label");

		this.labelMendixObject = labelMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Label.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static main.proxies.Label initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return main.proxies.Label.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static main.proxies.Label initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new main.proxies.Label(context, mendixObject);
	}

	public static main.proxies.Label load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return main.proxies.Label.initialize(context, mendixObject);
	}

	public static java.util.List<main.proxies.Label> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<main.proxies.Label> result = new java.util.ArrayList<main.proxies.Label>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Main.Label" + xpathConstraint))
			result.add(main.proxies.Label.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Confidence
	 */
	public final java.math.BigDecimal getConfidence()
	{
		return getConfidence(getContext());
	}

	/**
	 * @param context
	 * @return value of Confidence
	 */
	public final java.math.BigDecimal getConfidence(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Confidence.toString());
	}

	/**
	 * Set value of Confidence
	 * @param confidence
	 */
	public final void setConfidence(java.math.BigDecimal confidence)
	{
		setConfidence(getContext(), confidence);
	}

	/**
	 * Set value of Confidence
	 * @param context
	 * @param confidence
	 */
	public final void setConfidence(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal confidence)
	{
		getMendixObject().setValue(context, MemberNames.Confidence.toString(), confidence);
	}

	/**
	 * @return value of image_labels
	 */
	public final main.proxies.SlackImageRecognitionRequest getimage_labels() throws com.mendix.core.CoreException
	{
		return getimage_labels(getContext());
	}

	/**
	 * @param context
	 * @return value of image_labels
	 */
	public final main.proxies.SlackImageRecognitionRequest getimage_labels(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.SlackImageRecognitionRequest result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.image_labels.toString());
		if (identifier != null)
			result = main.proxies.SlackImageRecognitionRequest.load(context, identifier);
		return result;
	}

	/**
	 * Set value of image_labels
	 * @param image_labels
	 */
	public final void setimage_labels(main.proxies.SlackImageRecognitionRequest image_labels)
	{
		setimage_labels(getContext(), image_labels);
	}

	/**
	 * Set value of image_labels
	 * @param context
	 * @param image_labels
	 */
	public final void setimage_labels(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.SlackImageRecognitionRequest image_labels)
	{
		if (image_labels == null)
			getMendixObject().setValue(context, MemberNames.image_labels.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.image_labels.toString(), image_labels.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return labelMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final main.proxies.Label that = (main.proxies.Label) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Main.Label";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
