// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package awslex.actions;

import awslex.impl.LexResult;
import awslex.impl.MxAwsLexConnector;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class GetUtteranceIntent extends CustomJavaAction<java.lang.String>
{
	private java.lang.String AwsAccessKeyId;
	private java.lang.String AwsSecretAccessKey;
	private java.lang.String AwsRegion;
	private java.lang.String BotName;
	private java.lang.String BotAlias;
	private java.lang.String UserId;
	private java.lang.String Utterance;

	public GetUtteranceIntent(IContext context, java.lang.String AwsAccessKeyId, java.lang.String AwsSecretAccessKey, java.lang.String AwsRegion, java.lang.String BotName, java.lang.String BotAlias, java.lang.String UserId, java.lang.String Utterance)
	{
		super(context);
		this.AwsAccessKeyId = AwsAccessKeyId;
		this.AwsSecretAccessKey = AwsSecretAccessKey;
		this.AwsRegion = AwsRegion;
		this.BotName = BotName;
		this.BotAlias = BotAlias;
		this.UserId = UserId;
		this.Utterance = Utterance;
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
        //throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
        MxAwsLexConnector conn = new MxAwsLexConnector();
        conn.setLogger(logger);
        LexResult result = conn.getIntentForUtterance(this.AwsAccessKeyId, this.AwsSecretAccessKey, this.AwsRegion, this.BotName, this.BotAlias, this.UserId, this.Utterance);
        return result.getUtterance();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetUtteranceIntent";
	}

	// BEGIN EXTRA CODE
    private static final ILogNode logger = Core.getLogger(MxAwsLexConnector.LOGNODE_NAME);
	// END EXTRA CODE
}
