// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package awslex.actions;

import awslex.impl.MxAwsLexConnector;
import awslex.proxies.LexResult;
import awslex.proxies.Slot;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetUtteranceIntentDetails extends CustomJavaAction<IMendixObject>
{
	private java.lang.String AwsAccessKeyId;
	private java.lang.String AwsSecretAccessKey;
	private java.lang.String AwsRegion;
	private java.lang.String BotName;
	private java.lang.String BotAlias;
	private java.lang.String UserId;
	private java.lang.String Utterance;

	public GetUtteranceIntentDetails(IContext context, java.lang.String AwsAccessKeyId, java.lang.String AwsSecretAccessKey, java.lang.String AwsRegion, java.lang.String BotName, java.lang.String BotAlias, java.lang.String UserId, java.lang.String Utterance)
	{
		super(context);
		this.AwsAccessKeyId = AwsAccessKeyId;
		this.AwsSecretAccessKey = AwsSecretAccessKey;
		this.AwsRegion = AwsRegion;
		this.BotName = BotName;
		this.BotAlias = BotAlias;
		this.UserId = UserId;
		this.Utterance = Utterance;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
        //throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
        MxAwsLexConnector conn = new MxAwsLexConnector();
        conn.setLogger(logger);
        awslex.impl.LexResult lexResult = conn.getIntentForUtterance(this.AwsAccessKeyId, this.AwsSecretAccessKey, this.AwsRegion, this.BotName, this.BotAlias, this.UserId, this.Utterance);
        LexResult result = new LexResult(getContext());
        result.setIntent(getContext(),lexResult.getIntent());
        result.setDialogState(getContext(),lexResult.getDialogState());
        result.setMessage(getContext(),lexResult.getMessage());
        for(String key: lexResult.getSlots().keySet()) {
            Slot slot = new Slot(getContext());
            slot.setName(getContext(),key);
            slot.setValue(getContext(),lexResult.getSlots().get(key));
            slot.setSlot_LexResult(getContext(), result);
        }
        return result.getMendixObject();
        //return intent;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetUtteranceIntentDetails";
	}

	// BEGIN EXTRA CODE
    private static final ILogNode logger = Core.getLogger(MxAwsLexConnector.LOGNODE_NAME);
	// END EXTRA CODE
}
